<?php
/**
 * Theme for migrate content management form.
 */
function theme_mcontent_form_package(&$vars) {
  /*drupal_add_css(drupal_get_path('module', 'mcontent') . '/mcontent.css');
  drupal_add_js(drupal_get_path('module', 'mcontent') . '/mcontent.js');
  $output = '';
  $header = array(t('Entity'), t('Version'));
  $list_Entity = &$vars['form']['manage'];
  $output .= theme('table', array('header' => $header, 'rows' => $list_Entity, 'attributes' => array('id' => 'migrate-content-form-table', 'class' => array('migrate-content-manage'))));

  $output .= drupal_render($vars['form']['buttons']);
  $output .= drupal_render_children($vars['form']);
  return $output;*/
}